FROM ubuntu
RUN apt-get install python3 pip
RUN pip install virtualenv
RUN cd /home/$USER
COPY . /cc
RUN cd /home/$USER
RUN virtualenv cc && source cc/bin/activate
RUN pip install django djangorestframework psycopg2-binary django-keycloak-auth
RUN python3 ./frontend/manage.py runserver

