version: "3.11"

services:
# Databases
  cc_frontend_db:
    build: ./frontend_db/
    hostname: cc_frontend_db_host
    container_name: cc_frontend_db
    restart: always
    env_file:
     - .env
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    labels:
      - cc_frontend_db
    ports:
      - 5432
    networks:
      - cc_backend
    command: postgres
  cc_keycloak_db:
    build: ./keycloak_db/
    hostname: cc_keycloak_db_host
    container_name: cc_keycloak_db
    restart: always
    env_file:
      .env
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    labels:
      - cc_keycloak_db
    ports:
      - 5432
    networks:
      - cc_backend
    command: postgres
# Services
  cc_keycloak:
    build: ./keycloak/
    hostname: cc_keycloak_host
    container_name: cc_keycloak
    restart: always
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER:=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=4dm1n
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1

      - KEYCLOAK_DATABASE_HOST=cc_keycloak_db_host
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=bn_keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public.
      - KEYCLOAK_JDBC_PARAMS=sslmode=verify-full&connectTimeout=30000

      - KEYCLOAK_HTTP_PORT=8080.
      - KEYCLOAK_HTTPS_PORT=8443.
      - KEYCLOAK_BIND_ADDRESS=0.0.0.0
    depends_on:
      cc_keycloak_db:
        condition: service_started
    labels:
      - cc_keycloak
    ports: 
      - 8080:8080
      - 8443:8443
    networks:
      - cc_backend
      - cc_frontend
    command: start-dev
  cc_keycloak_rest_api:
    build: ./keycloak_rest_api/
    hostname: cc_keycloak_rest_api_host
    container_name: cc_keycloak_rest_api
    restart: always
    environment:
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      cc_keycloak:
        condition: service_started
    labels:
      - cc_keycloak_rest_api
    ports:
      - 8081:8081
    networks:
      - cc_backend
    volumes:
      - type: bind
        source: ./keycloak_rest_api
        target: /CC/CC/keycloak_rest_api
    command: bash -c "pip3 install -r /CC/CC/keycloak_rest_api/requirements.txt --no-cache-dir --root-user-action=ignore &&
                      cd /CC/CC/keycloak_rest_api/volume/ && python3 entrypoint.py"
  cc_frontend:
    build: ./frontend/
    hostname: cc_frontend_host
    container_name: cc_frontend
    environment:
     - DJANGO_SETTINGS_MODULE:cc_proyecto.settings
    restart: always
    depends_on:
      cc_frontend_db:
        condition: service_started
      cc_keycloak_rest_api:
        condition: service_started
    labels:
      - cc_frontend
    ports:
      - 8000:8000
    networks:
      - cc_frontend
      - cc_backend
    volumes:
      - type: bind
        source: ./frontend
        target: /CC/CC/frontend
    command: bash -c "source /CC/CC/frontend/cc_venv_frontend/bin/activate && 
                      pip3 install -r /CC/CC/frontend/requirements.txt --no-cache-dir --root-user-action=ignore &&
                      python3 /CC/CC/frontend/cc_proyecto/manage.py makemigrations cc_proyecto && 
                      python3 /CC/CC/frontend/cc_proyecto/manage.py migrate --no-input --run-syncdb && 
                      python3 /CC/CC/frontend/cc_proyecto/manage.py runserver 0.0.0.0:8000"
  cc_minio:
    build: ./minio/
    hostname: cc_minio_host
    container_name: cc_minio
    restart: always
    labels:
      - cc_minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - cc_backend
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - cc_minio_volume:/data
  cc_worker:
    build: ./worker/
    hostname: cc_worker_host
    container_name: cc_worker
    restart: always
    environment:
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      cc_minio:
        condition: service_started
    labels:
      - cc_worker
    ports:
      - 3000:3000
    networks:
      - cc_backend
    volumes:
      - type: bind
        source: ./worker
        target: /CC/CC/worker
    command: bash -c "cd /CC/CC && source /CC/CC/worker/cc_venv_worker/bin/activate && 
                      pip3 install -r /CC/CC/worker/requirements.txt --no-cache-dir --root-user-action=ignore &&
                      cd /CC/CC/worker/volume/ && uvicorn worker_api:app --reload --port=3000"
  cc_inyector:
    build: ./inyector/
    hostname: cc_inyector_host
    container_name: cc_inyector
    restart: always
    environment:
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      cc_kafka:
        condition: service_started
    labels:
      - cc_inyector
    ports:
      - 4000:4000
    networks:
      - cc_backend
    volumes:
      - type: bind
        source: ./inyector
        target: /CC/CC/inyector
    command: bash -c "cd /CC/CC && source /CC/CC/inyector/cc_venv_inyector/bin/activate && 
                      pip3 install -r /CC/CC/inyector/requirements.txt --no-cache-dir --root-user-action=ignore &&
                      cd /CC/CC/inyector/volume/ && uvicorn cc_inyector_api:app --reload --port=3000"
  cc_zookeeper:
    build: ./zookeeper/
    hostname: cc_zookeeper_host
    container_name: cc_zookeeper
    restart: always
    labels:
      - cc_zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
        - cc_backend
  cc_kafka:
    build: ./kafka/
    hostname: cc_kafka_host
    image: 'cc_kafka'
    container_name: cc_kafka
    restart: always
    environment:
      KAFKA_USERNAME: cc_kafka_admin
      KAFKA_PASSWORD: cc_4dm1n_p455
    depends_on:
      cc_zookeeper:
        condition: service_started
    labels:
      - cc_kafka
    ports:
      - 9092:9092
    networks:
      - cc_backend
  cc_kafka_ui:
    image: provectuslabs/kafka-ui
    container_name: cc_kafkaui
    ports:
      - 9093:9093
    restart: always
    depends_on:
      cc_kafka:
        condition: service_started
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=cc_kafka:9092
    networks:
      - cc_backend
  cc_kafka_client:
    build: ./kafka_client/
    hostname: cc_kafka_client_host
    image: 'cc_kafka_client'
    container_name: cc_kafka_client
    restart: always
    depends_on:
      cc_kafka:
        condition: service_started
    labels:
      - cc_kafka_client
    ports:
      - 9050:9050
    networks:
      - cc_backend
    volumes:
      - type: bind
        source: ./kafka_client
        target: /CC/CC/kafka_client
    command: bash -c "cd /CC/CC/kafka_client/volume/ && python3 kafka_main.py"
networks:
  cc_backend:
    name: cc_backend
    driver: bridge
  cc_frontend:
    name: cc_frontend
    driver: bridge
volumes:
  cc_minio_volume:
    name: cc_minio_vol
  cc_worker_volume:
    name: cc_worker_vol
