version: "3.9"
services:
  db:
    build: ./db/
    image: cc_postgres
    hostname: cc_postgres
    container_name: cc_postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - cc_backend
    ports:
      - 5432:5432
    command: postgres
  frontend:
    build: ./frontend/
    container_name: cc_frontend
    environment:
     - DJANGO_SETTINGS_MODULE=cc_proyecto.settings
    restart: always
    image: cc_frontend
    depends_on:
      db:
        condition: service_started
    ports:
      - 8000:8000
    networks:
      - cc_frontend
      - cc_backend
    command: bash -c "python manage.py makemigrations cc_proyecto && python manage.py migrate --no-input --run-syncdb && python manage.py runserver 0.0.0.0:8000"
networks:
  cc_backend:
    name: cc_backend
    driver: bridge
  cc_frontend:
    name: cc_frontend
    driver: bridge