version: '3'
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
    command:
      - apt-get update && apt-get install -y keycloak python3 python3-pip
      - pip3 install django
    depends_on:
      - db
    networks:
      - front_end
      - back_end
  kafka:
    build: ./kafka
    image: 'bitnami/zookeeper:latest'
    restart: always
    networks:
      - back_end
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "pendientes:1:1,completados:1:1"
    depends_on:
      - zookeeper
      - db
  zookeeper:
    build: ./zookeeper
    image: 'bitnami/zookeeper:latest'
    restart: always
    networks:
      - back_end
    depends_on:
      - db
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
  db:
    build: ./db
    image: postgres
    restart: always
    networks:
      - back_end
    command:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install django
    environment:
      - POSTGRES_USER=cloudcomputing-
      - POSTGRES_PASSWORD=cloudcomputing-
      - POSTGRES_DB=cc_db
    ports:
      - 5432:5432
    depends_on:
      - db
  observer:
    build: ./observer
    networks:
      - back_end
    restart: always
    command:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install django
    depends_on:
        - db
        - kafka
  worker:
    build: ./worker
    networks:
      - back_end
    restart: always
    command:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install django
    depends_on:
        - db
        - kafka
networks:
  front_end:
  back_end:
