version: '3'
services:
  frontend:
    build: .
    network: cc
    ports:
      - 8000:8000
    run:
      - apt-get update && apt-get install -y keycloak python3 python3-pip
      - pip3 install django
  kafka:
    build: .
    network: cc
    run:
      - apt-get update && apt-get install -y kafka python3 python3-pip
      - pip3 install django
  zookeeper:
    build: .
    network: cc
    run:
      - apt-get update && apt-get install -y zookeeper python3 python3-pip
      - pip3 install django
  db:
    build: .
    network: cc
    run:
      - apt-get update && apt-get install -y postgresql python3 python3-pip
      - pip3 install django
  observer:
    build: .
    network: cc
    run:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install django
  worker:
    build: .
    network: cc
    run:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install django

