FROM python:3.8
RUN apt-get update && apt-get install -y libpq-dev apache2
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
RUN a2enmod proxy_http
RUN a2enmod proxy
RUN a2enmod proxy_balancer
RUN a2enmod lbmethod_byrequests
COPY apache/000-default.conf /etc/apache2/sites-available/000-default.conf
EXPOSE 80
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

