# Generated by Django 4.1.5 on 2023-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repo', models.CharField(max_length=255)),
                ('url_repo', models.URLField()),
            ],
            options={
                'db_table': 'cc_cloud_repos',
            },
        ),
    ]
