# Generated by Django 3.2 on 2023-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_proyecto', '0003_alter_repo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='creation_timestamp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='inyector_timestamp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repo',
            name='worker_finishing_timestamp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='worker_start_timestamp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
