# Generated by Django 3.2 on 2023-02-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_proyecto', '0004_auto_20230129_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='nombre_repo',
        ),
    ]
