FROM python:3

EXPOSE 8081:8081

RUN mkdir -p /CC/CC/keycloak_rest_api/volume

WORKDIR /CC/CC/keycloak_rest_api/volume/

CMD chmod +x /CC/CC/keycloak_rest_api/volume/entrypoint.sh

#ENTRYPOINT ["python3", "entrypoint.py"]