"""
Django settings for cc_proyecto project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'srq@glu@+b)2yo5cj69q)w&94vt$27#(!rno*nudq(f+@gob+6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cc_proyecto',
    "corsheaders",
]

# AUTHENTICATION_BACKENDS = [
#         'django.contrib.auth.backends.ModelBackend',
#         'djangooidc.backends.OpenIdConnectBackend',
#     ]

# LOGIN_URL = 'openid'

# OIDC_DYNAMIC_CLIENT_REGISTRATION_DATA = {
#     "application_type": "web",
#     "contacts": ["lfqueram@posgrado.upv.es"],
#     "redirect_uris": ["http://cc_frontend_host:8080/openid/callback/login/", ],
#     "post_logout_redirect_uris": ["http://cc_frontend_host:8000/openid/callback/logout/", ]
# }

# OIDC_DEFAULT_BEHAVIOUR = {
#     "response_type": "code",
#     "scope": ["openid", "profile", "email", "address", "phone"],
# }

# OIDC_PROVIDERS = {
#     "Keycloak": {
#         "srv_discovery_url": "https://sts.windows.net/aaaaaaaa-aaaa-1111-aaaa-xxxxxxxxxxxxx/",
#         "behaviour": OIDC_DEFAULT_BEHAVIOUR,
#         "client_registration": {
#             "client_id": "cc_cliente",
#             "client_secret": "fu84AacHUShCwm5fPnh67IesjK1NNumx",
#             "redirect_uris": ["http://localhost:8000/openid/callback/login/"],
#             "post_logout_redirect_uris": ["http://localhost:8000/openid/callback/logout/"],
#             "token_endpoint_auth_method": "client_secret_post",
#         }
#     }
# }
# 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = 'cc_proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'cc_app/templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cc_proyecto.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "cc_cloud_db",
        'USER': "cc_cloud_user",
        'PASSWORD': "cc_cl0ud_p455",
        'HOST': 'cc_frontend_db_host',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
CORS_ORIGIN_ALLOW_ALL = True

